version: "3.8"

networks:
  local_network:
    name: local_network
    driver: bridge
    external: true

volumes:
  mysql-volume:
    driver: local

services:
  local_api:
    build: .
    container_name: local_api
    tty: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PHP_MEMORY_LIMIT: 256M
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/conf/local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${API_PORT}:80
    # depends_on:
    #   - local_redis
    #   - local_mysql
    networks:
      - local_network

  # local_memcached:
  #   image: memcached:latest
  #   container_name: local_memcached
  #   ports:
  #     - "11211:11211"

  # local_redis:
  #   image: "redis:7.2.4-alpine"
  #   container_name: local_redis
  #   command: redis-server
  #   volumes:
  #     - ./docker/redis/redis-data:/data
  #   environment:
  #     - REDIS_REPLICATION_MODE=master

  #   networks:
  #     - local_network

  # local_supervisor:
  #   container_name: local_supervisor
  #   build:
  #     context: docker
  #     dockerfile: supervisor.Dockerfile
  #     args:
  #       - APP_ROOT="/var/www/app"
  #       - COMMAND="horizon"
  #       - OPTIONS=""
  #   volumes:
  #     - ./:/var/www/app
  #     - ./docker/entrypoint/supervisor-init.sh:/usr/local/bin/supervisor-init.sh
  #     - ./docker/logs/supervisor:/var/log/supervisor
  #     - ./docker/worker/supervisord.conf:/etc/supervisord.conf
  #   entrypoint: >
  #     sh -c "/usr/bin/supervisord --nodaemon --configuration /etc/supervisord.conf && chmod 777 /usr/local/bin/supervisor-init.sh && exec /usr/local/bin/supervisor-init.sh"
  #   depends_on:
  #     - local_api

  # local_crontab:
  #   build:
  #     context: docker
  #     dockerfile: cron.Dockerfile
  #   container_name: local_crontab
  #   volumes:
  #     - ./:${WORK_DIR}
  #   networks:
  #     - local_network

  # local_mysql:
  #   image: mysql:8.0
  #   container_name: local_mysql
  #   platform: linux/amd64
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - ${MYSQL_PORT}:3306
  #   volumes:
  #     - mysql-volume:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: sb_main_db1
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #   networks:
  #     - local_network

  # local_phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: local_phpmyadmin
  #   security_opt:
  #     - no-new-privileges:true
  #   links:
  #     - local_mysql:local_mysql
  #   environment:
  #     PMA_HOST: local_mysql
  #   restart: unless-stopped
  #   depends_on:
  #     - local_mysql
  #   ports:
  #     - ${PHPMYADMIN_PORT}:80
  #   networks:
  #     - local_network
