version: "3.8"

networks:
  http_network:
    name: http_network
    driver: bridge
    external: true

services:
  testing_api:
    build: .
    container_name: testing_api
    tty: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PHP_MEMORY_LIMIT: 2G
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/conf/testing.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=http_network"
      - "traefik.http.services.testing_api.loadbalancer.server.port=80"
      - "traefik.http.routers.testing_api.entrypoints=websecure"
      - "traefik.http.routers.testing_api.tls.certresolver=le-dns"
      - "traefik.http.routers.testing_api.rule=Host(`testing-api.sicurobrands.com`)"
    links:
      - testing_redis
    depends_on:
      - testing_redis
    networks:
      - http_network

  testing_redis:
    image: "redis:latest"
    container_name: testing_redis
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--appendonly",
        "yes",
      ]
    volumes:
      - ./docker/redis/redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - http_network

  testing_supervisor:
    container_name: testing_supervisor
    build:
      context: docker
      dockerfile: supervisor.Dockerfile
      args:
        - APP_ROOT="/var/www/app"
        - COMMAND="horizon"
        - OPTIONS=""
    volumes:
      - ./:/var/www/app
      - ./docker/worker/supervisord.conf:/etc/supervisord.conf
      - ./docker/entrypoint/supervisor-init.sh:/usr/local/bin/supervisor-init.sh
      - ./docker/entrypoint/supervisor-entrypoint.sh:/usr/local/bin/supervisor-entrypoint.sh
      - ./docker/logs/supervisor:/var/log/supervisor
    entrypoint: >
      sh -c "/usr/bin/supervisord --nodaemon --configuration=/etc/supervisord.conf && chmod 0644 /usr/local/bin/supervisor-init.sh && exec /usr/local/bin/supervisor-init.sh"
    depends_on:
      - testing_api
    networks:
      - http_network

  testing_crontab:
    build:
      context: docker
      dockerfile: cron.Dockerfile
    container_name: testing_crontab
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      PHP_MEMORY_LIMIT: 2G
    networks:
      - http_network
